require("user.plugins")
require("user.gitsigns")
require("user.nvimtree")
require("user.options")
require("user.telescope")
require("user.completion")
require("user.treesitter")
require("user.hop")
require("user.feline") -- lualine
require("user.dadbod")
require("user.keymaps")
require("user.rest")
require("user.colorscheme")
require("user.lsp")
