alias l="ls -l"
alias ll="ls -l"
alias la="ls -la"
alias v="nvim -c Git -c +q"
alias lg="lazygit"
alias ccd="cd \"\$(findproject)\" && clear"
alias nchat="TERM=xterm-256color nchat"
alias tsm="transmission-remote"
