# history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
export HISTFILE="$HOME/.history"
export HISTSIZE=2000
export HISTORY_IGNORE="(mv*|cp*|mkdir*|ls*|lf*|cd*|clear|exit|rm*|v*|mpv*)"
export EDITOR="nvim"
