return {
    kind = {
        Text = "",
        Function = "",
        Constructor = "",
        Method = "",
        -- Function = "",
        -- Constructor = "",
        -- Method = "m",
        Field = "",
        Variable = "",
        -- Variable = "",
        Class = "",
        Interface = "",
        -- Module = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        -- Keyword = "",
        Keyword = "",
        -- Snippet = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
    },
    type = {
        Array = "",
        Number = "",
        String = "",
        Boolean = "蘒",
        Object = "",
    },
    documents = {
        File = "",
        Files = "",
        Folder = "",
        OpenFolder = "",
    },
    -- git = {
    --     unstaged = "",
    --     staged = "S",
    --     unmerged = "",
    --     renamed = "➜",
    --     deleted = "",
    --     untracked = "U",
    --     ignored = "◌",
    -- },
    git = {
        untracked = "",
        staged = "",
        deleted = "",
        ignored = "",
        renamed = "",
        unstaged = "",
        unmerged = "",
    },
    -- git = {
    --     Add = "",
    --     Mod = "",
    --     Remove = "",
    --     Ignore = "",
    --     Rename = "",
    --     Diff = "",
    --     Repo = "",
    -- },
    ui = {
        Lock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        Close = "",
        NewFile = "",
        Search = "",
        Lightbulb = "",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "",
        Note = "",
        BookMark = "",
        Pencil = "",
        ChevronRight = "",
        -- ChevronRight = ">",
        Table = "",
        Calendar = "",
    },
    -- diagnostics = {
    --     Error = "",
    --     Warning = "",
    --     Information = "",
    --     Question = "",
    --     Hint = "",
    -- },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "",
    },
    misc = {
        Robot = "ﮧ",
        Squirrel = "",
        Tag = "",
        Watch = "",
    },
}

