[manager]
show_hidden = true
mouse_events = ['click', 'scroll', 'touch', 'move', 'drag']

[opener]
edit = [ { run = 'nvim "$@"', block = true, for = "unix" } ]
play = [ { run = 'mpv "$@"', orphan = true, for = "unix" } ]
open = [ { run = 'xdg-open "$@"', desc = "Open" } ]
