[mgr]
show_hidden = true
mouse_events = ['click', 'scroll', 'touch', 'move', 'drag']

[opener]
edit  = [ { run = 'nvim "$@"', block = true, for = "unix" } ]
play  = [ { run = 'mpv "$@"', orphan = true, for = "unix" } ]
pdf   = [ { run = 'zathura "$@"', orphan = true, for = "unix" } ]
image = [ { run = 'imv "$@"', orphan = true, for = "unix" } ]
rar   = [ { run = 'unrar x "$@"', orphan = true, for = "unix" } ]
zip   = [ { run = 'unzip -o "$@"', orphan = true, for = "unix" } ]

[open]
rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
	{ mime = "application/pdf", use = "pdf" },
	{ name = "*.rar", use = "rar" },
	{ name = "*.zip", use = "zip" },
]
