[manager]
show_hidden = true
mouse_events = ['click', 'scroll', 'touch', 'move', 'drag']

[opener]
edit  = [ { run = 'nvim "$@"', block = true, for = "unix" } ]
play  = [ { run = 'mpv "$@"', orphan = true, for = "unix" } ]
image = [ { run = 'feh "$@"', desc = "Open" } ]
open  = [ { run = 'xdg-open "$@"', desc = "Open" } ]

[open]
rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
]
