version: '3.8'

services:
  glance:
    container_name: glance
    image: glanceapp/glance
    ports: 
      - 8090:8090
    volumes:
      - ./glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
